spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?options=-c%20timezone=America/Bogota
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: inventory_schema
        jdbc:
          time_zone: America/Bogota
    database-platform: org.hibernate.dialect.PostgreSQLDialect

product:
  api:
    base-url: http://localhost:8080

server:
  port: 8081